In [1]:
print("Working!")

Working!

In [2]:
import pandas as pd

movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

movies.head()

ModuleNotFoundError: No module named 'pandas'

In [ ]:
!pip install pandas

In [ ]:
!pip install pandas

In [ ]:
!pip install pandas

In [ ]:
!pip install numpy scikit-learn scipy

In [1]:
import pandas as pd

ImportError: C extension: pandas.util not built. If you want to import pandas from the source directory, you may need to run 'python -m pip install -ve . --no-build-isolation -Ceditable-verbose=true' to build the C extensions first.

In [2]:
import sys
!{sys.executable} -m pip install pandas

Collecting pandas
  Using cached pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.1

In [2]:
!pip uninstall pandas -y
!pip install pandas==2.2.2

WARNING: Skipping pandas as it is not installed.

Collecting pandas==2.2.2
  Using cached pandas-2.2.2.tar.gz (4.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [12 lines of output]
  + meson setup C:\Users\shwet\AppData\Local\Temp\pip-install-ck_08fbe\pandas_e3d2361114c745d79ea5fd2d9bdeb469 C:\Users\shwet\AppData\Local\Temp\pip-install-ck_08fbe\pandas_e3d2361114c745d79ea5fd2d9bdeb469\.mesonpy-hl5p2hzu\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\shwet\AppData\Local\Temp\pip-install-ck_08fbe\pandas_e3d2361114c745d79ea5fd2d9bdeb469\.mesonpy-hl5p2hzu\build\meson-python-native-file.ini
  The Meson build system
  Version: 1.2.1
  Source dir: C:\Users\shwet\AppData\Local\Temp\pip-install-ck_08fbe\pandas_e3d2361114c745d79ea5fd2d9bdeb469
  Build dir: C:\Users\shwet\AppData\Local\Temp\pip-install-ck_08fbe\pandas_e3d2361114c745d79ea5fd2d9bdeb469\.mesonpy-hl5p2hzu\build
  Build type: native build
  Project name: pandas
  Project version: 2.2.2

  ..\..\meson.build:2:0: ERROR: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

  A full log can be found at C:\Users\shwet\AppData\Local\Temp\pip-install-ck_08fbe\pandas_e3d2361114c745d79ea5fd2d9bdeb469\.mesonpy-hl5p2hzu\build\meson-logs\meson-log.txt
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

pandas

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [1]:
import pandas as pd
print(pd.__version__)

ModuleNotFoundError: No module named 'pandas'

In [2]:
!pip install --upgrade --force-reinstall pandas numpy

Collecting pandas
  Using cached pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Using cached numpy-2.4.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached numpy-2.4.3-cp314-cp314-win_amd64.whl (12.4 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, six, numpy, python-dateutil, pandas

  Attempting uninstall: tzdata

    Found existing installation: tzdata 2025.3

   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
    Uninstalling tzdata-2025.3:
   ---------------------------------------- 0/5 [tzdata]
      Successfully uninstalled tzdata-2025.3
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
  Attempting uninstall: six
   ---------------------------------------- 0/5 [tzdata]
    Found existing installation: six 1.17.0
   ---------------------------------------- 0/5 [tzdata]
    Uninstalling six-1.17.0:
   ---------------------------------------- 0/5 [tzdata]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
      Successfully uninstalled six-1.17.0
   -------- ------------------------------- 1/5 [six]
   -------- ------------------------------- 1/5 [six]
  Attempting uninstall: numpy
   -------- ------------------------------- 1/5 [six]
    Found existing installation: numpy 2.4.3
   -------- ------------------------------- 1/5 [six]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
    Uninstalling numpy-2.4.3:
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
      Successfully uninstalled numpy-2.4.3
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
   ---------------- ----------------------- 2/5 [numpy]
  Attempting uninstall: python-dateutil
   ---------------- ----------------------- 2/5 [numpy]
    Found existing installation: python-dateutil 2.9.0.post0
   ---------------- ----------------------- 2/5 [numpy]
    Uninstalling python-dateutil-2.9.0.post0:
   ---------------- ----------------------- 2/5 [numpy]
   ------------------------ --------------- 3/5 [python-dateutil]
      Successfully uninstalled python-dateutil-2.9.0.post0
   ------------------------ --------------- 3/5 [python-dateutil]
   ------------------------ --------------- 3/5 [python-dateutil]
   ------------------------ --------------- 3/5 [python-dateutil]
   ------------------------ --------------- 3/5 [python-dateutil]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   -------------------------------- ------- 4/5 [pandas]
   ---------------------------------------- 5/5 [pandas]


  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\shwet\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [ ]:
import sys
!{sys.executable} -m pip install pandas numpy scikit-learn scipy

In [1]:
import pandas as pd
print(pd.__version__)

3.0.1

In [2]:
import pandas as pd

movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

movies.head()

FileNotFoundError: [Errno 2] No such file or directory: 'movies.csv'

In [1]:
import os
os.listdir()

['.config',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.nbi',
 '.vscode',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'CrossDevice',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'mern-study-platform',
 'movie recommendation',
 'movie-recommendation',
 'movie_recommendation.ipynb',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TM.blf',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Postman',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Videos',
 'WPS Cloud Files']

In [1]:
import os
os.listdir()

['.config',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.nbi',
 '.vscode',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'CrossDevice',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'mern-study-platform',
 'movie recommendation',
 'movie-recommendation',
 'movie_recommendation.ipynb',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TM.blf',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Postman',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Videos',
 'WPS Cloud Files']

In [2]:
import pandas as pd

movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

movies.head()

FileNotFoundError: [Errno 2] No such file or directory: 'movies.csv'

In [2]:
import os
os.listdir()

['.config',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.nbi',
 '.vscode',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'CrossDevice',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'mern-study-platform',
 'movie recommendation',
 'movie-recommendation',
 'movie_recommendation.ipynb',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TM.blf',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{f4ac2a56-0db4-11f1-87c2-9409ccab9455}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'Postman',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Videos',
 'WPS Cloud Files']

In [3]:
import pandas as pd

movies = pd.read_csv(r"C:\Users\shwet\Downloads\ml-latest-small (1)\ml-latest-small\movies.csv")
ratings = pd.read_csv(r"C:\Users\shwet\Downloads\ml-latest-small (1)\ml-latest-small\ratings.csv")

movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.4.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 3.4 MB/s eta 0:00:11
   - -------------------------------------- 1.0/37.3 MB 3.0 MB/s eta 0:00:13
   - -------------------------------------- 1.8/37.3 MB 3.1 MB/s eta 0:00:12
   -- ------------------------------------- 2.6/37.3 MB 3.5 MB/s eta 0:00:10
   --- ------------------------------------ 3.7/37.3 MB 3.8 MB/s eta 0:00:09
   ----- ---------------------------------- 5.0/37.3 MB 4.1 MB/s eta 0:00:08
   ------ --------------------------------- 6.0/37.3 MB 4.3 MB/s eta 0:00:08
   ------- -------------------------------- 7.3/37.3 MB 4.5 MB/s eta 0:00:07
   --------- ------------------------------ 8.7/37.3 MB 4.7 MB/s eta 0:00:07
   ---------- ----------------------------- 10.0/37.3 MB 4.9 MB/s eta 0:00:06
   ------------ --------------------------- 11.3/37.3 MB 5.0 MB/s eta 0:00:06
   ------------- -------------------------- 12.6/37.3 MB 5.2 MB/s eta 0:00:05
   -------------- ------------------------- 13.6/37.3 MB 5.1 MB/s eta 0:00:05
   --------------- ------------------------ 14.7/37.3 MB 5.2 MB/s eta 0:00:05
   ----------------- ---------------------- 16.0/37.3 MB 5.2 MB/s eta 0:00:05
   ------------------ --------------------- 17.6/37.3 MB 5.3 MB/s eta 0:00:04
   -------------------- ------------------- 19.1/37.3 MB 5.4 MB/s eta 0:00:04
   --------------------- ------------------ 20.2/37.3 MB 5.4 MB/s eta 0:00:04
   ---------------------- ----------------- 21.2/37.3 MB 5.5 MB/s eta 0:00:03
   ------------------------ --------------- 22.5/37.3 MB 5.4 MB/s eta 0:00:03
   ------------------------- -------------- 23.9/37.3 MB 5.5 MB/s eta 0:00:03
   -------------------------- ------------- 24.6/37.3 MB 5.5 MB/s eta 0:00:03
   --------------------------- ------------ 25.4/37.3 MB 5.4 MB/s eta 0:00:03
   ---------------------------- ----------- 26.5/37.3 MB 5.3 MB/s eta 0:00:03
   ----------------------------- ---------- 27.3/37.3 MB 5.3 MB/s eta 0:00:02
   ------------------------------ --------- 28.0/37.3 MB 5.2 MB/s eta 0:00:02
   ------------------------------- -------- 29.1/37.3 MB 5.2 MB/s eta 0:00:02
   ------------------------------- -------- 29.4/37.3 MB 5.2 MB/s eta 0:00:02
   -------------------------------- ------- 30.4/37.3 MB 5.1 MB/s eta 0:00:02
   --------------------------------- ------ 30.9/37.3 MB 5.0 MB/s eta 0:00:02
   --------------------------------- ------ 31.5/37.3 MB 4.9 MB/s eta 0:00:02
   ---------------------------------- ----- 32.5/37.3 MB 4.9 MB/s eta 0:00:01
   ----------------------------------- ---- 33.0/37.3 MB 4.9 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/37.3 MB 4.8 MB/s eta 0:00:01
   ------------------------------------ --- 34.3/37.3 MB 4.8 MB/s eta 0:00:01
   ------------------------------------- -- 34.9/37.3 MB 4.7 MB/s eta 0:00:01
   ------------------------------------- -- 35.4/37.3 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 36.2/37.3 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  36.7/37.3 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  37.0/37.3 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 4.4 MB/s  0:00:08
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

In [5]:
import pandas as pd

movies = pd.read_csv(r"C:\Users\shwet\Downloads\ml-latest-small (1)\ml-latest-small\movies.csv")
ratings = pd.read_csv(r"C:\Users\shwet\Downloads\ml-latest-small (1)\ml-latest-small\ratings.csv")

# Merge data
data = pd.merge(ratings, movies, on='movieId')

# Create matrix
movie_matrix = data.pivot_table(index='userId', columns='title', values='rating')
movie_matrix = movie_matrix.fillna(0)

movie_matrix.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(movie_matrix.T)
similarity_df = pd.DataFrame(similarity, index=movie_matrix.columns, columns=movie_matrix.columns)

similarity_df.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.141653,0.0,...,0.0,0.342055,0.543305,0.707107,0.0,0.0,0.139431,0.327327,0.0,0.0
'Hellboy': The Seeds of Creation (2004),0.0,1.000000,0.707107,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Round Midnight (1986),0.0,0.707107,1.000000,0.000000,0.000000,0.0,0.176777,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Salem's Lot (2004),0.0,0.000000,0.000000,1.000000,0.857493,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Til There Was You (1997),0.0,0.000000,0.000000,0.857493,1.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0

In [7]:
def recommend(movie_name):
    return similarity_df[movie_name].sort_values(ascending=False).head(10)

In [8]:
recommend("Toy Story (1995)")

title
Toy Story (1995)                                     1.000000
Toy Story 2 (1999)                                   0.572601
Jurassic Park (1993)                                 0.565637
Independence Day (a.k.a. ID4) (1996)                 0.564262
Star Wars: Episode IV - A New Hope (1977)            0.557388
Forrest Gump (1994)                                  0.547096
Lion King, The (1994)                                0.541145
Star Wars: Episode VI - Return of the Jedi (1983)    0.541089
Mission: Impossible (1996)                           0.538913
Groundhog Day (1993)                                 0.534169
Name: Toy Story (1995), dtype: float64

In [9]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [44 lines of output]

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
          self.avg_cltr_i = avg_cltr_i
          self.avg_cocltr = avg_cocltr

          return self

      def compute_averages(self, np.ndarray[np.int_t] cltr_u,
                                               ^
  ------------------------------------------------------------
  surprise\prediction_algorithms\co_clustering.pyx:157:45: Invalid type.
  Compiling surprise/similarities.pyx because it changed.
  Compiling surprise/prediction_algorithms/matrix_factorization.pyx because it changed.
  Compiling surprise/prediction_algorithms/optimize_baselines.pyx because it changed.
  Compiling surprise/prediction_algorithms/slope_one.pyx because it changed.
  Compiling surprise/prediction_algorithms/co_clustering.pyx because it changed.
  [1/5] Cythonizing surprise/prediction_algorithms/co_clustering.pyx
  Traceback (most recent call last):
    File "C:\Users\shwet\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
      main()
      ~~~~^^
    File "C:\Users\shwet\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\shwet\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\shwet\AppData\Local\Temp\pip-build-env-k0ryy6ib\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\shwet\AppData\Local\Temp\pip-build-env-k0ryy6ib\overlay\Lib\site-packages\setuptools\build_meta.py", line 301, in _get_build_requires
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "C:\Users\shwet\AppData\Local\Temp\pip-build-env-k0ryy6ib\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 116, in <module>
    File "C:\Users\shwet\AppData\Local\Temp\pip-build-env-k0ryy6ib\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1153, in cythonize
      cythonize_one(*args)
      ~~~~~~~~~~~~~^^^^^^^
    File "C:\Users\shwet\AppData\Local\Temp\pip-build-env-k0ryy6ib\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1297, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: surprise/prediction_algorithms/co_clustering.pyx
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'scikit-surprise' when getting requirements to build wheel

In [10]:
from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split

# Load dataset
reader = Reader(rating_scale=(0.5, 5))
data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader)

# Split data
trainset, testset = train_test_split(data, test_size=0.2)

ModuleNotFoundError: No module named 'surprise'

In [11]:
import numpy as np

# Create matrix
matrix = movie_matrix.values

# Apply SVD
U, sigma, Vt = np.linalg.svd(matrix, full_matrices=False)

# Convert sigma to diagonal matrix
sigma = np.diag(sigma)

# Reconstruct matrix
predicted_ratings = np.dot(np.dot(U, sigma), Vt)

pred_df = pd.DataFrame(predicted_ratings, columns=movie_matrix.columns)

pred_df.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
0,2.855789e-16,-1.203790e-15,-4.024558e-16,-3.747003e-16,-6.800116e-16,-2.836273e-16,1.222980e-15,1.125185e-15,4.135581e-15,2.345346e-15,...,-1.336821e-16,-3.226586e-16,-1.089406e-15,-6.661338e-16,-4.915773e-16,4.780898e-15,-1.249001e-15,-5.481726e-16,4.000000e+00,-1.441989e-16
1,-1.358288e-15,-3.694961e-16,7.632783e-17,7.771561e-16,4.440892e-16,3.929149e-16,8.290243e-15,1.444157e-16,4.690692e-15,-3.941292e-15,...,-2.385245e-16,-4.551914e-15,-1.214306e-15,-1.870032e-15,-3.018419e-16,1.360023e-15,-2.720046e-15,-4.857226e-16,2.803313e-15,-1.604619e-17
2,5.221518e-16,7.945034e-16,9.992007e-16,-1.804112e-16,-4.024558e-16,-1.085937e-15,2.331468e-15,7.962381e-16,-7.209511e-15,-1.318390e-16,...,9.584347e-17,-4.996004e-16,-3.504141e-16,-3.755676e-16,-3.486794e-16,2.474583e-15,-3.011480e-15,1.630640e-16,1.373901e-15,5.204170e-17
3,5.282233e-16,1.023487e-16,1.374335e-15,2.914335e-16,6.791442e-16,-1.459282e-15,-2.393918e-15,1.086804e-15,2.706169e-15,6.383782e-16,...,2.354887e-16,-4.996004e-16,4.709774e-16,1.916869e-16,3.118165e-16,1.436351e-15,-1.844011e-15,-3.729655e-16,2.764282e-15,1.821460e-17
4,-1.346145e-15,-5.204170e-16,-1.144917e-15,2.914335e-15,7.632783e-16,-1.630640e-16,-3.441691e-15,2.688821e-16,-2.414735e-15,1.040834e-15,...,1.237075e-16,-1.693090e-15,-2.636780e-16,-6.028164e-16,-3.807718e-16,7.535639e-15,6.869505e-16,-2.619432e-16,6.395925e-15,6.722053e-17

In [12]:
def recommend_svd_simple(movie_name):
    return pred_df[movie_name].sort_values(ascending=False).head(10)

In [13]:
recommend_svd_simple("Toy Story (1995)")

246    5.0
379    5.0
165    5.0
95     5.0
410    5.0
452    5.0
532    5.0
395    5.0
30     5.0
176    5.0
Name: Toy Story (1995), dtype: float64

In [14]:
def recommend_svd_simple(movie_name):
    similar_scores = pred_df[movie_name].sort_values(ascending=False).head(10)
    
    # convert index to movie names
    return similar_scores.reset_index().rename(columns={'index': 'Movie', movie_name: 'Score'})

In [15]:
recommend_svd_simple("Toy Story (1995)")

   Movie  Score
0    246    5.0
1    379    5.0
2    165    5.0
3     95    5.0
4    410    5.0
5    452    5.0
6    532    5.0
7    395    5.0
8     30    5.0
9    176    5.0

In [16]:
def recommend_svd_simple(movie_name):
    # get similarity scores from cosine (correct movie similarity)
    similar_movies = similarity_df[movie_name].sort_values(ascending=False).head(10)
    
    # convert to table
    return similar_movies.reset_index().rename(columns={'title': 'Movie', movie_name: 'Score'})

In [17]:
recommend_svd_simple("Toy Story (1995)")

                                               Movie     Score
0                                   Toy Story (1995)  1.000000
1                                 Toy Story 2 (1999)  0.572601
2                               Jurassic Park (1993)  0.565637
3               Independence Day (a.k.a. ID4) (1996)  0.564262
4          Star Wars: Episode IV - A New Hope (1977)  0.557388
5                                Forrest Gump (1994)  0.547096
6                              Lion King, The (1994)  0.541145
7  Star Wars: Episode VI - Return of the Jedi (1983)  0.541089
8                         Mission: Impossible (1996)  0.538913
9                               Groundhog Day (1993)  0.534169